cubes:
  - name: leads
    sql_table: public.leads
    data_source: default

    joins:
      - name: accounts
        sql: "{CUBE}.id = {accounts}.id"
        relationship: many_to_one

      - name: tasks
        sql: "{CUBE}.id = {tasks}.related_to_id AND {tasks}.related_to_type = 'lead'"
        relationship: one_to_many

      - name: campaigns
        sql: "{CUBE}.id = {campaigns}.id"
        relationship: many_to_one

    dimensions:
      - name: id
        sql: id
        type: number
        primary_key: true

      - name: first_name
        sql: first_name
        type: string

      - name: last_name
        sql: last_name
        type: string

      - name: full_name
        sql: CONCAT(${first_name}, ' ', ${last_name})
        type: string
        description: "Concatenated first and last name for ease of use in reports."

      - name: email
        sql: email
        type: string

      - name: phone
        sql: phone
        type: string

      - name: company
        sql: company
        type: string

      - name: status
        sql: status
        type: string

      - name: created_at
        sql: created_at
        type: time

    measures:
      - name: count
        type: count
        description: "Counts the total number of leads."
